version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest   
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

  customer-ms:
    image: customer-ms:latest    
    container_name: customer-ms
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8080"
    networks:
      - ms-network

  sales-ms:
    image: sales-ms:latest
    container_name: sales-ms
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8080"
    networks:
      - ms-network

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8088:8080"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
